services:
  kafka:
    container_name: kafka
    image: quay.io/strimzi/kafka:latest-kafka-3.3.2
    command:
      [
        "sh",
        "-c",
        "export CLUSTER_ID=$$(bin/kafka-storage.sh random-uuid) && bin/kafka-storage.sh format -t $$CLUSTER_ID -c config/kraft/server.properties && bin/kafka-server-start.sh config/kraft/server.properties --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} --override listeners=$${KAFKA_LISTENERS}",
      ]
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
    networks:
      - demo-net
  artemis:
    container_name: artemis-local
    image: localhost/artemis
    ports:
      - "5672:5672"
      - "61616:61616"
    environment:
      AMQ_USER: "admin"
      AMQ_PASSWORD: "admin"
    networks:
      - demo-net
  ai-ml-engine:
    container_name: ai-ml-engine-local
    image: quay.io/redhatintegration/object-detection
    ports:
      - 8095:8080
    networks:
      - demo-net
  price-engine:
    container_name: price-engine-local
    image: quay.io/redhatintegration/camel-price:1.0.0
    ports:
      - 8090:18090
    networks:
      - demo-net
networks:
  demo-net: {}
