yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers:  edge-kafka-bootstrap.edge.svc:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
