kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: broker-amq-mqtt
  namespace: edge
spec:
  to:
    kind: Service
    name: edge-mqtt-0-svc
    weight: 100
  port:
    targetPort: mqtt-0
  tls:
    termination: edge
  wildcardPolicy: None